# Generated by Django 3.1.4 on 2020-12-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='DOB',
            field=models.DateField(blank=True, max_length=12, null=True),
        ),
    ]
