# Generated by Django 3.1.4 on 2020-12-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiuser', '0002_auto_20201229_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='address',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
