# Generated by Django 3.1.4 on 2020-12-30 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regiuser', '0005_auto_20201230_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='userType',
            field=models.CharField(default='Customer', max_length=12),
        ),
        migrations.CreateModel(
            name='sellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneSeller', models.CharField(blank=True, max_length=12)),
                ('addressSeller', models.TextField(max_length=500, null=True)),
                ('userType', models.CharField(default='Seller', max_length=12)),
                ('userSeller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellerProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
