# Generated by Django 3.1.4 on 2020-12-30 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regiuser', '0006_auto_20201230_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='herbProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField(max_length=150)),
                ('productImage', models.ImageField(upload_to='')),
                ('productPrice', models.TextField()),
                ('sellername', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herbProduct', to='regiuser.userprofiles')),
            ],
        ),
    ]
