# Generated by Django 3.1.4 on 2020-12-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regiuser', '0007_herbproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbproduct',
            name='productDesc',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='herbproduct',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='herbproduct',
            name='productPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='herbproduct',
            name='sellername',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herbProduct', to='regiuser.sellerprofile'),
        ),
    ]
