# Generated by Django 3.1.4 on 2020-12-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiuser', '0008_auto_20201231_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbproduct',
            name='productDesc',
            field=models.TextField(),
        ),
    ]
