# Generated by Django 3.1.4 on 2020-12-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiuser', '0013_auto_20201231_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbproduct',
            name='productImage',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
