# Generated by Django 3.1.4 on 2020-12-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiuser', '0014_auto_20201231_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbproduct',
            name='productImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
