# Generated by Django 3.1.4 on 2020-12-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiuser', '0016_auto_20201231_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbproduct',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
